### ISSUE TITLE
local host error

### ISSUE THREAD

**Issue by kevinzxc1217** [luhsra/llfree-bench#1]
Hello:

I've successfully executed ssh -p2222 user@localhost and navigated to the llfree-bench directory within Docker. However, when attempting to run ./run.py bench kernel, I consistently encounter the error message ssh: connect to host localhost port 5222: Cannot assign requested address. Could you please assist me in resolving this issue?

Thank you.

**Comment by wrenger** [comment]
Unfortunately, I'm not really able to reproduce your problem. During the artifact evaluation, the only issue that came up was that the container needs permissions to access `/dev/kvm` (of the host) to correctly start the contained VMs.

Did you execute `./run.py` inside the container (in ~/llfree-bench)?

**Comment by kevinzxc1217** [comment]
Yes, I successfully accessed the container using the command `ssh -p 2222 user@localhost`, and within the container, I successfully executed `./run.py build all`. However, when I executed the command `./run.py bench kernel -m 32 -c 8`, an error occurred, as shown in the picture. Should the port of the program or command be changed?

Thanks

![error](https://github.com/luhsra/llfree-bench/assets/125337691/580e3c8c-2662-43d3-82b8-80252992bb14)

**Comment by wrenger** [comment]
Does `frag/artifact-bu/error.txt` exist? If so, it contains a more detailed error message.

**Comment by kevinzxc1217** [comment]
Yes, thank you for your help.

**Comment by wrenger** [comment]
Let me know if you still encounter problems :)
